# Generated by Django 3.1.3 on 2020-12-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201202_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='bio',
            field=models.TextField(max_length=2000),
        ),
    ]
