# Generated by Django 3.1.2 on 2020-10-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_generator', '0002_auto_20201023_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armour_name', models.CharField(max_length=20)),
                ('armour_type', models.IntegerField(choices=[(0, 'light'), (1, 'medium'), (2, 'heavy')])),
                ('armour_ac', models.PositiveSmallIntegerField()),
                ('armour_max_dex', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Weapons',
            new_name='Weapon',
        ),
        migrations.AlterField(
            model_name='charclass',
            name='fort_save_ratio',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='charclass',
            name='reflex_save_ratio',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='charclass',
            name='will_save_ratio',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Armours',
        ),
    ]
