# Generated by Django 3.1.2 on 2020-10-23 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npc_generator', '0003_auto_20201023_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='weapon_list',
        ),
    ]
