# Generated by Django 3.1.2 on 2020-10-23 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc_generator', '0004_remove_weapon_weapon_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armourproficiencylist',
            name='char_class',
        ),
        migrations.RemoveField(
            model_name='weaponproficiencylist',
            name='char_class',
        ),
        migrations.AddField(
            model_name='charclass',
            name='armour_proficiencies',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='npc_generator.armourproficiencylist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charclass',
            name='weapon_proficiencies',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='npc_generator.weaponproficiencylist'),
            preserve_default=False,
        ),
    ]
