# Generated by Django 3.1.2 on 2020-10-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npc_generator', '0005_auto_20201023_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charclass',
            name='armour_proficiencies',
        ),
        migrations.RemoveField(
            model_name='charclass',
            name='weapon_proficiencies',
        ),
    ]
