# Generated by Django 3.1.2 on 2020-10-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc_generator', '0006_auto_20201023_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='charclass',
            name='armour_proficiencies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='npc_generator.armourproficiencylist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charclass',
            name='weapon_proficiencies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='npc_generator.weaponproficiencylist'),
            preserve_default=False,
        ),
    ]
