# Generated by Django 3.1.2 on 2020-10-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc_generator', '0007_auto_20201023_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_list_name', models.CharField(max_length=20)),
                ('proficiency_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npc_generator.weaponproficiencylist')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npc_generator.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='ListedArmour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_list_name', models.CharField(max_length=20)),
                ('proficiency_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npc_generator.armourproficiencylist')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='npc_generator.armour')),
            ],
        ),
    ]
