# Generated by Django 3.1.2 on 2020-10-25 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('npc_generator', '0008_listedarmour_listedweapon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listedarmour',
            old_name='weapon',
            new_name='armour',
        ),
        migrations.AlterField(
            model_name='charclass',
            name='armour_proficiencies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='npc_generator.armourproficiencylist'),
        ),
        migrations.AlterField(
            model_name='charclass',
            name='weapon_proficiencies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='npc_generator.weaponproficiencylist'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_damage',
            field=models.CharField(max_length=10),
        ),
    ]
