# Generated by Django 3.1.2 on 2020-10-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc_generator', '0009_auto_20201025_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='charclass',
            name='primary_ability',
            field=models.IntegerField(choices=[(1, 'Strength'), (2, 'Dexterity'), (3, 'Constitution'), (4, 'Intelligence'), (5, 'Wisdom'), (6, 'Charisma')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charclass',
            name='secondary_ability',
            field=models.IntegerField(choices=[(1, 'Strength'), (2, 'Dexterity'), (3, 'Constitution'), (4, 'Intelligence'), (5, 'Wisdom'), (6, 'Charisma')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charclass',
            name='tertiary_ability',
            field=models.IntegerField(choices=[(1, 'Strength'), (2, 'Dexterity'), (3, 'Constitution'), (4, 'Intelligence'), (5, 'Wisdom'), (6, 'Charisma')], default=3),
            preserve_default=False,
        ),
    ]
